### ISSUE TITLE
Avoid breaks in ingredient list items

### ISSUE THREAD

**Issue by blackketter** [poundifdef/plainoldrecipe#10]
I don't have a way to test a patch locally, but I found that adding this to the @screen style improves the layout of the ingredients:

```
            li {
                -webkit-column-break-inside: avoid;
                page-break-inside: avoid;
                break-inside: avoid;
            }
```

**Comment by poundifdef** [comment]
Awesome! Looks good to me locally, just pushed a change to master to incorporate it.
