### ISSUE TITLE
Bypass test of enabled JS 

### ISSUE THREAD

**Issue by hotfix** [poundifdef/plainoldrecipe#12]
some websites checks the JS support and blocks the request if its not exists. 
e.g. https://www.rewe.de/rezepte

if i try to add a parser i get as response 

` <h1 data-translate="turn_on_js" style="color:#bd2426;">Please turn JavaScript on and reload the page.</h1>`

**Comment by poundifdef** [comment]
Interesting! How would you suggest solving for this specific website?

**Comment by hotfix** [comment]
i'm new to python, but probably one of the solutions could help
https://stackoverflow.com/questions/8049520/web-scraping-javascript-page-with-python

i will try it

**Comment by poundifdef** [comment]
I will close this issue for now. If you (or anyone) decides to take it up and has a relatively straightforward implementation, feel free to reopen and I'd love to hear about how you want to approach it.
