### ISSUE TITLE
Bookmarklet

### ISSUE THREAD

**Issue by blackketter** [poundifdef/plainoldrecipe#13]
Might be nice to have a bookmarklet on the home page.  I've found this useful:

`javascript:void(window.open('https://plainoldrecipe.com/recipe?url='+location.href.replace(/%5C/$/,%20'')));`

**Comment by poundifdef** [comment]
Okay. I've gone ahead an added a bookmarklet using your code. Is this what you were thinking? https://plainoldrecipe.com/

**Comment by blackketter** [comment]
Sure, that works!
