### ISSUE TITLE
what sites are popular with plainoldrecipe but aren't supported yet

### ISSUE THREAD

**Issue by blackketter** [poundifdef/plainoldrecipe#17]
Would it be possible to log the sites that folks are trying to use and post statistics to help prioritize which parsers might be most useful?

**Comment by prediscover** [comment]
Please add https://thatlowcarblife.com/ !

**Comment by chrispinkney** [comment]
Going to repaste my comment here from #46:

In regards to adding some sort of logging feature:

How about keeping a Google spreadsheet (which I've never used but imagine has a ton of fun analytics to work with) and just updating it with the `domain` that failed [just before here](https://github.com/poundifdef/plainoldrecipe/blob/master/main.py#L53)? I found [this which might be of help](https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html). Seems promising.

Or via use of a bot deployed on heroku's free tier (_but I don't think the free tier gives enough hours to cover the entire month, I tried to make a discord bot once and had that issue_) that updates a GitHub issue with unsupported domains?

I think Firebase also has a free option but I don't know anything about it (or about GCP tbh) beyond the name, haha.

![firefox_2020-11-03_14-39-31](https://user-images.githubusercontent.com/7242003/98032774-810f2580-1de2-11eb-8144-fae5bbb3d771.png)

What do you think?

**Comment by poundifdef** [comment]
Hello! I've added this. You can see the page here: https://plainoldrecipe.com/statistics

Code is here: https://github.com/poundifdef/plainoldrecipe/commit/f43b5f40a0777bed64e65d666fa7dfc6590613de

Using https://www.scratchdb.com to store data. We'll see how it goes, if there is spam then I'll have to disable the feature.
