### ISSUE TITLE
Instructions to run locally

### ISSUE THREAD

**Issue by blackketter** [poundifdef/plainoldrecipe#23]
Sorry if this a dumb question, but is there a way to run plainoldrecipe locally without deploying to gcloud as described in the README.md?

**Comment by poundifdef** [comment]
Yes! What is your comfort level with python and pip? (Just to know where to begin with instructions!)

**Comment by blackketter** [comment]
Not a strong python programmer, but happy to install and run via command line.  Also happy to try it out and give feedback. :)

**Comment by himynameisdave** [comment]
I'm also not the strongest python programmer, but was able to get it up and running locally fairly easily. I'd be happy to open a PR here to add this documentation to the README. 💪
