### ISSUE TITLE
Broken recipe: realsimple.com

### ISSUE THREAD

**Issue by himynameisdave** [poundifdef/plainoldrecipe#51]
Found a broken recipe, where no directions/ingredients are displayed:

https://www.plainoldrecipe.com/recipe?url=https%3A%2F%2Fwww.realsimple.com%2Ffood-recipes%2Fbrowse-all-recipes%2Fmustard-pork-chops

Perhaps this will be fixed by updating the scrapers dependency, but if not I don't mind digging into why this is failing.

**Comment by poundifdef** [comment]
Thanks for this! I tried updating the dependency locally, however, the site still did not work. Feel free to make a pull request!

**Comment by poundifdef** [comment]
Looks like this was fixed in 2021 https://github.com/hhursev/recipe-scrapers/pull/320
