### ISSUE TITLE
Website offline 

### ISSUE THREAD

**Issue by vjandrea** [poundifdef/plainoldrecipe#69]
The website is offline, did the domain name expire?

**Comment by poundifdef** [comment]
It had expired, yes. I just renewed it! (Would anyone be willing to help donate to make it a little easier for me to keep online?)

**Comment by vjandrea** [comment]
@poundifdef why don't you setup a Github Sponsors profile ? Or a Patreon account ?

**Comment by poundifdef** [comment]
Good idea! Let's see if this works: https://github.com/sponsors/poundifdef
