### ISSUE TITLE
Error Fetching Recipe

### ISSUE THREAD

**Issue by MaxRickettsUy** [poundifdef/plainoldrecipe#85]
Revisted this bookmarked page and got the error:

https://plainoldrecipe.com/recipe?url=https%3A%2F%2Fwww.spendwithpennies.com%2Foven-baked-chicken-breasts%2F

Then tried a random recipe from one of the other supported sites and received the same error.

**Comment by poundifdef** [comment]
Thanks for catching this - should be fixed now. I'd made some updates this weekend and accidentally broke the page.
